'use client';
import {useEffect,useState,ReactNode} from 'react';
import {LockKeyhole,ArrowRight} from 'lucide-react';
export default function Access({scope,children}:{scope:'staff'|'customers'|'owner'|'admin';children:ReactNode}){
 const [ready,setReady]=useState(false),[loading,setLoading]=useState(true),[pin,setPin]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{if(scope==='admin'){setLoading(false);return}let live=true;fetch('/api/auth?scope='+scope).then(r=>r.json()).then((d:any)=>{if(live){setReady(!!d.authorized);setError(d.error||'')}}).catch(()=>live&&setError('Tidak dapat memeriksa akses.')).finally(()=>live&&setLoading(false));return()=>{live=false}},[scope]);
 async function unlock(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({scope,pin})});const d=await r.json() as any;if(!r.ok)throw Error(d.error);setPin('');if(scope==='admin'){location.href=d.redirect;return}setReady(true)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 if(loading)return <main className="access"><p>Memeriksa akses…</p></main>;if(ready)return <>{children}</>;
 return <main className="access"><a href="/"><img src="/itwash-logo.png" width="160" alt="iT Wash"/></a><div className="access-box"><LockKeyhole size={28}/><h1>{scope==='admin'?'Admin':scope==='staff'?'Area karyawan':scope==='customers'?'Data pelanggan':'Dashboard owner'}</h1><p>Masukkan PIN untuk melanjutkan.</p><form onSubmit={unlock}><label>PIN<input autoFocus type="password" inputMode="numeric" autoComplete="off" pattern="[0-9]+" maxLength={12} required value={pin} onChange={e=>setPin(e.target.value)}/></label>{error&&<p className="error" role="alert">{error}</p>}<button className="primary" disabled={busy}>{busy?'Memeriksa…':'Buka akses'}<ArrowRight size={18}/></button></form><a className="back-link" href={scope==='customers'?'/karyawan':'/'}>Kembali</a></div></main>
}
