'use client';
import {useEffect,useState} from 'react';
import {Download,Share2} from 'lucide-react';
export default function CustomInvoice(){
 const [brand,setBrand]=useState('itwash');
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[file,setFile]=useState<File|null>(null),[url,setUrl]=useState(''),[shareable,setShareable]=useState(false);
 const [when]=useState(()=>new Date(Date.now()+7*3600000).toISOString().slice(0,16));
 useEffect(()=>{if(!file){setUrl('');return}const u=URL.createObjectURL(file);setUrl(u);setShareable(!!navigator.canShare?.({files:[file]}));return()=>URL.revokeObjectURL(u)},[file]);
 async function create(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);setBusy(true);setError('');setFile(null);try{const r=await fetch('/api/invoice',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...Object.fromEntries(form),amount:Number(form.get('amount')),confirmPaid:form.get('confirmPaid')==='on'})});if(!r.ok){const d=await r.json() as any;throw Error(d.error||'Invoice belum dapat dibuat.')}const name=r.headers.get('Content-Disposition')?.match(/filename="([^"]+)"/)?.[1]||'Invoice-iTWash-LUNAS.pdf';setFile(new File([await r.blob()],name,{type:'application/pdf'}))}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function share(){if(!file)return;setError('');try{await navigator.share({files:[file],title:'Invoice LUNAS '+(brand==='itworks'?'iTworks':'iT Wash')})}catch(e){if((e as Error).name!=='AbortError')setError('Gunakan Unduh PDF lalu lampirkan sebagai Dokumen di WhatsApp.')}}
 return <section className="queue custom-invoice"><h2>Invoice custom</h2><p className="lead">Pilih iT Wash untuk cucian atau iTworks untuk aksesori mobil.</p><p className="field-note">PDF ini dibuat terpisah dan tidak menambah transaksi penjualan atau antrean cucian. Unduh untuk menyimpan salinannya.</p><form className="entry" onSubmit={create} onChange={()=>{setFile(null);setError('')}}><fieldset disabled={busy} className="entry"><div className="invoice-brand"><label>Logo invoice<select name="brand" value={brand} onChange={e=>setBrand(e.target.value)}><option value="itwash">iT Wash — Cucian</option><option value="itworks">iTworks — Aksesori mobil</option></select></label><img src={brand==='itworks'?'/itworks-logo.png':'/itwash-logo.png'} alt={brand==='itworks'?'iTworks':'iT Wash'} /></div><div className="form-grid"><label>Nama pelanggan<input name="customerName" required maxLength={100} placeholder="Nama pelanggan"/></label><label>Plat kendaraan<input name="plate" required maxLength={20} placeholder="KB1234XX" autoCapitalize="characters"/></label><label>Jenis mobil<input name="vehicle" required maxLength={100} placeholder="Contoh: Toyota Fortuner"/></label><label>Produk / layanan<input name="product" required maxLength={160} placeholder={brand==='itworks'?'Contoh: Karpet mobil':'Contoh: Premium Wash'}/></label><label>Nominal (Rp)<input name="amount" type="number" inputMode="numeric" required min={0} max={100000000} step={1} placeholder="120000"/></label><label>Metode pembayaran<select name="paymentMethod" required defaultValue="tunai"><option value="tunai">Tunai</option><option value="qris">QRIS</option><option value="transfer">Transfer</option></select></label><label>Tanggal invoice & pembayaran<input name="date" type="date" required defaultValue={when.slice(0,10)}/></label><label>Waktu pembayaran (WIB)<input name="time" type="time" required defaultValue={when.slice(11)}/></label></div><label className="paid-confirm"><input type="checkbox" name="confirmPaid" required/><span>Saya mengonfirmasi pembayaran sudah diterima sesuai nominal dan waktu di atas.</span></label></fieldset>{error&&<p className="error" role="alert">{error}</p>}<button className="primary" disabled={busy}>{busy?'Membuat invoice…':'Buat invoice LUNAS'}</button></form>{file&&<div className="custom-invoice-result" role="status"><p className="notice">Invoice LUNAS siap. Unduh atau bagikan PDF kepada pelanggan.</p><div className="invoice-actions"><a className="secondary" href={url} download={file.name}><Download size={18}/>Unduh PDF</a>{shareable&&<button className="primary" onClick={share}><Share2 size={18}/>Bagikan PDF</button>}</div><p className="field-note">Untuk WhatsApp, pilih Bagikan PDF atau unduh lalu lampirkan file sebagai Dokumen.</p></div>}</section>
}
