'use client';
import {useEffect,useState} from 'react';
import {Search,MessageCircle,ArrowRight} from 'lucide-react';
import {Table,TableHeader,TableHead,TableBody,TableRow,TableCell} from '@/components/ui/table';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Header,Footer} from './shell';
import {Job,dateTime,itemTitle,itemDetail,labels,normalizePhone} from '../lib/wash';
type Customer={phone:string;name:string;items:number;visits:number;lastVisit:number};
export default function CustomerData({embedded=false}:{embedded?:boolean}){
 const [rows,setRows]=useState<Customer[]>([]),[query,setQuery]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true),[selected,setSelected]=useState<Customer|null>(null),[history,setHistory]=useState<Job[]>([]),[detailLoading,setDetailLoading]=useState(false),[detailError,setDetailError]=useState('');
 async function load(){setError('');try{const r=await fetch('/api/customers');const d=await r.json() as any;if(!r.ok)throw Error(d.error);setRows(d.customers)}catch(e){setError((e as Error).message)}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 async function select(c:Customer){setSelected(c);setHistory([]);setDetailError('');setDetailLoading(true);try{const r=await fetch('/api/customers?phone='+encodeURIComponent(c.phone));const d=await r.json() as any;if(!r.ok)throw Error(d.error);setHistory(d.jobs)}catch(e){setDetailError((e as Error).message)}finally{setDetailLoading(false)}}
 const shown=rows.filter(c=>(c.name+' '+c.phone).toLowerCase().includes(query.toLowerCase())||(normalizePhone(query)&&normalizePhone(query)===c.phone));
 return <>{!embedded&&<Header staff/>}<div className={embedded?'customer-data embedded':'customer-data page-main'}><div className="heading"><div><span className="eyebrow">DATA PELANGGAN</span><h1>Kenali pelanggan Anda.</h1><p className="lead">Satu nomor HP, satu pelanggan. Riwayat nama tetap tersimpan pada setiap cucian.</p></div></div><section className="queue"><div className="queue-top"><h2>{rows.length} pelanggan</h2><label className="search"><Search size={18}/><input aria-label="Cari nama atau HP pelanggan" placeholder="Cari nama atau nomor HP" value={query} onChange={e=>setQuery(e.target.value)}/></label></div>{error&&<div className="error">{error}<button onClick={load}>Coba lagi</button></div>}{loading?<div className="empty">Memuat pelanggan…</div>:<Table className="mobile-cards customer-table"><TableHeader><TableRow><TableHead>Pelanggan</TableHead><TableHead>No. HP / WhatsApp</TableHead><TableHead>Kunjungan</TableHead><TableHead>Terakhir datang</TableHead><TableHead>Riwayat</TableHead></TableRow></TableHeader><TableBody>{shown.map(c=><TableRow key={c.phone}><TableCell data-label="Pelanggan" className="font-semibold">{c.name||'Nama belum tersedia'}</TableCell><TableCell data-label="No. HP / WhatsApp"><a className="whatsapp text-link" href={'https://wa.me/'+c.phone} target="_blank" rel="noopener noreferrer"><MessageCircle size={16}/>{c.phone}</a></TableCell><TableCell data-label="Kunjungan">{c.visits} kali · {c.items} cucian</TableCell><TableCell data-label="Terakhir datang">{dateTime(c.lastVisit)}</TableCell><TableCell data-label="Riwayat"><button className="secondary" onClick={()=>select(c)}>Lihat<ArrowRight size={16}/></button></TableCell></TableRow>)}</TableBody></Table>}{!loading&&!shown.length&&<div className="empty">Belum ada pelanggan yang sesuai.</div>}</section></div>{!embedded&&<Footer/>}<Dialog open={!!selected} onOpenChange={v=>{if(!v)setSelected(null)}}><DialogContent className="wash-dialog"><DialogTitle>Riwayat {selected?.name}</DialogTitle><DialogDescription>{selected?.phone} · Semua kunjungan berdasarkan nomor HP ini.</DialogDescription>{detailLoading?<p>Memuat riwayat…</p>:detailError?<p className="error">{detailError}</p>:history.map(j=><article className="history-item" key={j.id}><div><h3>{itemTitle(j)}</h3><p>{itemDetail(j)}</p><small>Nama saat masuk: {j.customerName}<br/>{dateTime(j.created)}</small></div><span className={j.voidedAt?'void-badge':'badge s'+j.status}>{j.voidedAt?'Void':labels[j.status]}</span></article>)}</DialogContent></Dialog></>
}
