'use client';
import {useEffect,useState} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Download,Share2,MessageCircle} from 'lucide-react';
import {Job,itemTitle,waLink,normalizePhone} from '../lib/wash';
export default function InvoiceDialog({job,onClose}:{job:Job|null;onClose:()=>void}){
 const [file,setFile]=useState<File|null>(null),[url,setUrl]=useState(''),[error,setError]=useState(''),[shareable,setShareable]=useState(false),[busy,setBusy]=useState(false);
 useEffect(()=>{if(!job)return;let active=true,objectUrl='';setFile(null);setUrl('');setError('');setShareable(false);
 fetch('/api/invoice?id='+encodeURIComponent(job.id)).then(async r=>{if(!r.ok){const d=await r.json() as any;throw Error(d.error)}return r.blob()}).then(blob=>{if(!active)return;const f=new File([blob],'ITW-'+(job.groupId||job.id).toUpperCase()+'-LUNAS.pdf',{type:'application/pdf'});objectUrl=URL.createObjectURL(f);setFile(f);setUrl(objectUrl);setShareable(!!navigator.canShare?.({files:[f]}))}).catch(e=>{if(active)setError(e.message)});
 return()=>{active=false;if(objectUrl)URL.revokeObjectURL(objectUrl)};
 },[job]);
 async function share(){if(!file||!job)return;setBusy(true);setError('');try{await navigator.share({files:[file],title:'Invoice iT Wash',text:'Halo pelanggan iTwash, berikut invoice LUNAS cucian Anda. Pembayaran sudah kami terima. Terima kasih.'})}catch(e){if((e as Error).name!=='AbortError')setError('PDF belum dibagikan. Gunakan Unduh PDF lalu lampirkan di WhatsApp.')}finally{setBusy(false)}}
 return <Dialog open={!!job} onOpenChange={v=>{if(!v)onClose()}}><DialogContent className="checkout-dialog"><DialogTitle>Invoice LUNAS & WhatsApp</DialogTitle><DialogDescription>{job?itemTitle(job):''} · {job?.customerName}<br/>{normalizePhone(job?.phone)}</DialogDescription>{error&&<p className="error" role="alert">{error}</p>}{!file&&!error?<p role="status">Menyiapkan invoice LUNAS…</p>:file&&<><p className="field-note">{job?.category==='sepatu'?'Semua sepatu aktif dalam pesanan ini digabung dalam satu invoice. ':' '}Seluruh pembayaran pesanan ini sudah tercatat lunas.</p><div className="invoice-actions">{shareable&&<button className="primary" onClick={share} disabled={busy}><Share2 size={18}/>Bagikan PDF</button>}<a className="secondary" href={url} download={file.name}><Download size={18}/>Unduh PDF</a>{job&&waLink(job)&&<a className="whatsapp" href={waLink(job)+'?text='+encodeURIComponent('Halo pelanggan iTwash, berikut invoice LUNAS cucian Anda. Pembayaran sudah kami terima. Terima kasih.')} target="_blank" rel="noopener noreferrer"><MessageCircle size={18}/>Buka chat WhatsApp</a>}</div><p className="field-note">{shareable?'Pilih WhatsApp dan kontak pelanggan pada menu Bagikan PDF. ':'Unduh PDF, buka chat WhatsApp, lalu lampirkan PDF sebagai Dokumen. '}Tombol Buka chat tidak otomatis melampirkan file. Periksa penerima sebelum mengirim.</p></>}</DialogContent></Dialog>
}
