'use client';
import {useEffect,useState} from 'react';
import {Table,TableHeader,TableHead,TableBody,TableRow,TableCell} from '@/components/ui/table';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import CustomerData from './customer-data';
import {Header,Footer} from './shell';
import {money,dateTime} from '../lib/wash';
type Transaction={id:string;category:string;plate:string;brand:string;color:string;washType:string;amount:number;paidAt:number;paymentMethod:string;voidedAt:number|null;voidReason:string};
type Data={totals:{day:number;week:number;month:number};breakdown:{category:string;washType:string;count:number;revenue:number}[];transactions:Transaction[];outstanding:{count:number;amount:number;unpriced:number}};
const segments=[{scope:'staff',title:'Area karyawan',description:'Akses antrean, pencatatan cucian, dan pembayaran.'},{scope:'customers',title:'Data pelanggan',description:'Akses nomor HP dan riwayat pelanggan di area karyawan.'},{scope:'owner',title:'Dashboard owner',description:'Akses penjualan, void transaksi, dan pengaturan PIN.'}];
export default function OwnerDashboard(){
 const [period,setPeriod]=useState('day'),[section,setSection]=useState('sales'),[data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[loading,setLoading]=useState(true),[refresh,setRefresh]=useState(0),[busy,setBusy]=useState(false);
 const [voiding,setVoiding]=useState<Transaction|null>(null),[reason,setReason]=useState(''),[voidError,setVoidError]=useState('');
 const [pinScope,setPinScope]=useState<typeof segments[number]|null>(null),[newPin,setNewPin]=useState(''),[confirmPin,setConfirmPin]=useState(''),[pinError,setPinError]=useState('');
 useEffect(()=>{let live=true;async function load(){try{const r=await fetch('/api/owner?period='+period);const d=await r.json() as any;if(!r.ok)throw Error(d.error);if(live){setData(d);setError('')}}catch(e){if(live)setError((e as Error).message)}finally{if(live)setLoading(false)}}setLoading(true);void load();const t=setInterval(load,15000);return()=>{live=false;clearInterval(t)}},[period,refresh]);
 async function voidTransaction(){if(!voiding)return;setBusy(true);setVoidError('');try{const r=await fetch('/api/owner',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'void',id:voiding.id,reason})});const d=await r.json() as any;if(!r.ok)throw Error(d.error);setVoiding(null);setNotice('Transaksi di-void dan tidak lagi dihitung dalam penjualan.');setRefresh(n=>n+1)}catch(e){setVoidError((e as Error).message)}finally{setBusy(false)}}
 async function changePin(e:React.FormEvent){e.preventDefault();if(!pinScope)return;setBusy(true);setPinError('');try{const r=await fetch('/api/owner',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'change_pin',scope:pinScope.scope,pin:newPin,confirmPin})});const d=await r.json() as any;if(!r.ok)throw Error(d.error);setNewPin('');setConfirmPin('');setPinScope(null);if(d.relogin){location.href='/owner';return}setNotice('PIN berhasil diganti. Bagian tersebut meminta PIN baru saat dibuka kembali.')}catch(e){setPinError((e as Error).message)}finally{setBusy(false)}}
 return <><Header/><main><div className="heading"><div><span className="eyebrow">DASHBOARD OWNER</span><h1>Ruang owner</h1><p className="lead">Penjualan dan pengaturan akses iT Wash.</p></div><button className="secondary" onClick={async()=>{await fetch('/api/auth',{method:'DELETE'});location.href='/'}}>Kunci akses</button></div><Tabs value={section} onValueChange={setSection}><TabsList className="filters"><TabsTrigger value="sales">Penjualan</TabsTrigger><TabsTrigger value="customers">Data pelanggan</TabsTrigger><TabsTrigger value="pins">Pengaturan PIN</TabsTrigger></TabsList></Tabs>{notice&&<p className="notice" role="status">{notice}</p>}{error&&<p className="error">{error}</p>}
 {section==='customers'?<CustomerData embedded/>:section==='pins'?<section className="pin-settings"><h2>PIN per bagian</h2><p className="lead">Ganti PIN hanya untuk bagian yang dipilih. Gunakan 4–8 angka.</p><div className="pin-grid">{segments.map(s=><article className="pin-card" key={s.scope}><h3>{s.title}</h3><p>{s.description}</p><button className="secondary" onClick={()=>{setPinScope(s);setNewPin('');setConfirmPin('');setPinError('')}}>Ganti PIN</button></article>)}</div></section>:<><p className="field-note" style={{margin:'20px 0'}}>Pembayaran diterima, di luar transaksi void · WIB · Minggu dimulai Senin</p><div className="summary sales-summary">{[['day','Hari ini'],['week','Minggu ini'],['month','Bulan ini']].map(([key,label])=><button className={'stat '+(period===key?'stat1':'')} key={key} onClick={()=>setPeriod(key)}><span className="stat-label">{label}</span><strong>{data?money(data.totals[key as keyof Data['totals']]):'—'}</strong><span className="stat-bottom">Pembayaran diterima</span></button>)}</div><Tabs value={period} onValueChange={setPeriod}><TabsList className="filters"><TabsTrigger value="day">Hari ini</TabsTrigger><TabsTrigger value="week">Minggu ini</TabsTrigger><TabsTrigger value="month">Bulan ini</TabsTrigger></TabsList></Tabs>
 {loading?<div className="empty">Memuat penjualan…</div>:data&&<><div className="sales-layout"><section className="queue sales-card"><h2>Penjualan berdasarkan layanan</h2>{data.breakdown.length===0?<p className="field-note">Belum ada pembayaran pada periode ini.</p>:data.breakdown.map(b=><div className="revenue-row" key={b.category+b.washType}><div><strong>{b.category==='sepatu'?'Sepatu':b.category==='motor'?'Motor':'Mobil'} {b.washType}</strong><span>{b.count} cucian</span></div><strong>{money(b.revenue)}</strong></div>)}</section><section className="queue sales-card"><h2>Belum dibayar</h2><strong className="outstanding-number">{data.outstanding.count} cucian</strong><p>{money(data.outstanding.amount)} dari harga yang sudah terisi.</p>{data.outstanding.unpriced>0&&<p className="field-note">{data.outstanding.unpriced} cucian belum memiliki harga.</p>}<small>Semua tanggal. Tidak termasuk dalam penjualan di atas.</small></section></div><section className="queue"><div className="queue-top"><h2>Rincian pembayaran <span>{data.transactions.filter(t=>!t.voidedAt).length} aktif</span></h2></div><Table className="mobile-cards sales-table"><TableHeader><TableRow><TableHead>Waktu pembayaran</TableHead><TableHead>Cucian</TableHead><TableHead>Layanan</TableHead><TableHead>Metode</TableHead><TableHead>Nominal</TableHead><TableHead>Tindakan</TableHead></TableRow></TableHeader><TableBody>{data.transactions.map(t=><TableRow key={t.id} className={t.voidedAt?'void-row':''}><TableCell data-label="Waktu pembayaran">{dateTime(t.paidAt)}</TableCell><TableCell data-label="Cucian">{t.category==='sepatu'?t.brand+' · '+t.color:t.plate}</TableCell><TableCell data-label="Layanan">{t.category} {t.washType}</TableCell><TableCell data-label="Metode">{t.paymentMethod==='qris'?'QRIS':'Tunai'}</TableCell><TableCell data-label="Nominal" className="font-semibold">{money(t.amount)}</TableCell><TableCell data-label="Tindakan">{t.voidedAt?<span className="void-badge" title={t.voidReason+' · '+dateTime(t.voidedAt)}>Void</span>:<button className="void-button" onClick={()=>{setVoiding(t);setReason('');setVoidError('')}}>Void transaksi</button>}</TableCell></TableRow>)}</TableBody></Table>{!data.transactions.length&&<div className="empty">Belum ada pembayaran yang dicatat.</div>}</section></>}
 </>}
 </main><Footer/>
 <Dialog open={!!pinScope} onOpenChange={v=>{if(!v&&!busy)setPinScope(null)}}><DialogContent><DialogTitle>Ganti PIN {pinScope?.title}</DialogTitle><DialogDescription>Sesi bagian ini akan dikunci setelah PIN diganti.{pinScope?.scope==='owner'?' Anda perlu masuk kembali dengan PIN owner baru.':''}</DialogDescription><form className="entry" onSubmit={changePin}><label>PIN baru<input className="pin-input" autoFocus type="password" inputMode="numeric" autoComplete="new-password" required pattern="[0-9]{4,8}" minLength={4} maxLength={8} value={newPin} onChange={e=>setNewPin(e.target.value)}/></label><label>Ulangi PIN baru<input className="pin-input" type="password" inputMode="numeric" autoComplete="new-password" required pattern="[0-9]{4,8}" minLength={4} maxLength={8} value={confirmPin} onChange={e=>setConfirmPin(e.target.value)}/></label>{pinError&&<p className="error" role="alert">{pinError}</p>}<button className="primary" disabled={busy}>{busy?'Menyimpan…':'Simpan PIN baru'}</button></form></DialogContent></Dialog>
 <AlertDialog open={!!voiding} onOpenChange={v=>{if(!v&&!busy)setVoiding(null)}}><AlertDialogContent><AlertDialogTitle>Void transaksi ini?</AlertDialogTitle><AlertDialogDescription>{voiding?(voiding.category==='sepatu'?voiding.brand+' · '+voiding.color:voiding.plate)+' — '+money(voiding.amount):''}. Transaksi dikeluarkan dari penjualan dan antrean. Riwayat pembatalan tetap tersimpan. Pengembalian uang, jika diperlukan, dilakukan terpisah.</AlertDialogDescription><label className="entry">Catatan (opsional)<input maxLength={200} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Contoh: transaksi tercatat dua kali"/></label>{voidError&&<p className="error" role="alert">{voidError}</p>}<AlertDialogFooter><AlertDialogCancel disabled={busy}>Batal</AlertDialogCancel><AlertDialogAction disabled={busy} className="void-button" onClick={e=>{e.preventDefault();void voidTransaction()}}>{busy?'Memproses…':'Ya, void transaksi'}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </>
}
