import {Car,Bike,Footprints,Sparkles} from 'lucide-react';
import {CAR_PRICES,CAR_PACKAGES,CAR_EXAMPLES,PACKAGE_DETAILS,MOTOR_PRICES,ADD_ON_PRICES,SHOE_PRICE} from '../lib/pricing';
import {money} from '../lib/wash';
export default function Pricelist(){return <section className="pricelist" aria-labelledby="pricelist-title">
 <div className="pricelist-heading"><span className="eyebrow">LAYANAN & HARGA</span><h2 id="pricelist-title">Daftar harga iT Wash</h2><p>Pilih kelas kendaraan, lalu paket perawatannya.</p></div>
 <article className="price-card car-pricelist"><div className="price-card-title"><Car size={24}/><h3>Mobil</h3></div><p className="price-unit">Harga per kendaraan · Pilih Luar, Full, atau Plus+</p>
 <div className="package-descriptions">{CAR_PACKAGES.map(p=><div key={p}><strong>{p}</strong><p>{PACKAGE_DETAILS[p]}</p></div>)}</div>
 <div className="car-price-grid">{Object.entries(CAR_PRICES).map(([name,prices])=><div className="car-price-class" key={name}><h4>{name}</h4><p>{CAR_EXAMPLES[name]}</p><dl>{CAR_PACKAGES.map(p=><div key={p}><dt>{p}</dt><dd>{money(prices[p])}</dd></div>)}</dl></div>)}</div></article>
 <div className="price-cards"><article className="price-card"><div className="price-card-title"><Bike size={24}/><h3>Motor</h3></div><p className="price-unit">Per kendaraan</p><dl>{Object.entries(MOTOR_PRICES).filter(([name])=>name!=='Karyawan').map(([name,price])=><div key={name}><dt>{name}</dt><dd>{money(price)}</dd></div>)}</dl><p className="shoe-eta-note">Basic: body wash, wheels & tires, drying.<br/>Super & Big Bike: ditambah detail clean.</p></article>
 <article className="price-card"><div className="price-card-title"><Footprints size={24}/><h3>Sepatu</h3></div><p className="price-unit">Per pasang · Deep clean, wash & care, drying</p><dl><div><dt>Cuci sepatu</dt><dd>{money(SHOE_PRICE)}</dd></div></dl><p className="shoe-eta-note">Estimasi selesai 48 jam sejak masuk.</p></article>
 <article className="price-card"><div className="price-card-title"><Sparkles size={24}/><h3>Layanan tambahan</h3></div><p className="price-unit">Tambahan perawatan mobil</p><dl>{Object.entries(ADD_ON_PRICES).map(([name,price])=><div key={name}><dt>{name}</dt><dd>{money(price)}</dd></div>)}</dl><p className="shoe-eta-note">GLACO front glass coating sudah termasuk dalam paket Plus+.</p></article></div></section>}
