'use client';
import {useEffect,useState} from 'react';
import {Droplets,Car,Plus,ArrowRight,Clock,Check,Search,Copy,RefreshCw,Bike,Footprints,Trash2,QrCode,MessageCircle,Wallet} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {Job,labels,itemTitle,itemDetail,normalizePhone,waLink,money,dateTime,dayKey,dayLabel} from '../lib/wash';
import {Header,Footer} from './shell';
import Pricelist from './pricelist';
import WashingCounts from './washing-counts';
import InvoiceDialog from './invoice-dialog';
import {priceFor,CAR_PRICES,CAR_PACKAGES,CAR_EXAMPLES,PACKAGE_DETAILS,ADD_ON_PRICES,carService,MOTOR_PRICES,SHOE_PRICE} from '../lib/pricing';
type Shoe={key:string;brand:string;color:string};
const emptyShoe=():Shoe=>({key:crypto.randomUUID(),brand:'',color:''});
function ItemIcon({category}:{category?:string}){const Icon=category==='sepatu'?Footprints:category==='motor'?Bike:Car;return <Icon size={26}/>}
const icons=[Clock,Droplets,Check];
export default function Carwash({customer=false}:{customer?:boolean}){
 const [jobs,setJobs]=useState<Job[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[filter,setFilter]=useState('active'),[query,setQuery]=useState(''),[open,setOpen]=useState(false),[busy,setBusy]=useState(false);
 const [code,setCode]=useState(''),[trackingKey,setTrackingKey]=useState(''),[tracked,setTracked]=useState<Job[]>([]);
 const [category,setCategory]=useState('mobil'),[customerName,setCustomerName]=useState(''),[phone,setPhone]=useState(''),[plate,setPlate]=useState(''),[vehicle,setVehicle]=useState(''),[washType,setWashType]=useState('Basic'),[carClass,setCarClass]=useState('Deluxe'),[carPackage,setCarPackage]=useState('Luar'),[extras,setExtras]=useState<string[]>([]),[shoes,setShoes]=useState<Shoe[]>([{key:'first',brand:'',color:''}]),[formError,setFormError]=useState(''),[existing,setExisting]=useState<{name:string;visits:number}|null>(null);
 const [invoice,setInvoice]=useState<Job|null>(null);
 const [qris,setQris]=useState(false),[pay,setPay]=useState<Job|null>(null),[payAmount,setPayAmount]=useState(''),[method,setMethod]=useState('qris'),[payError,setPayError]=useState(''),[checkout,setCheckout]=useState(false);
 const canInvoice=(j:Job)=>j.status>=2&&!!j.paidAt&&(j.category!=='sepatu'||!j.groupId||jobs.filter(row=>row.groupId===j.groupId).every(row=>!!row.paidAt&&row.amount!==null));
 async function refresh(){try{const r=await fetch('/api/jobs');const d=await r.json() as any;if(!r.ok)throw Error(d.error);setJobs(d.jobs);setError('')}catch(e){setError((e as Error).message)}finally{setLoading(false)}}
 async function lookup(value:string){if(!value.trim())return;setBusy(true);try{const r=await fetch('/api/track?code='+encodeURIComponent(value.trim()));const d=await r.json() as any;if(!r.ok)throw Error(d.error);setTracked(d.jobs||[d.job]);setTrackingKey(value);setError('');return d.jobs||[d.job]}catch(e){setTracked([]);setError((e as Error).message);throw e}finally{setBusy(false);setLoading(false)}}
 useEffect(()=>{if(customer){const c=new URLSearchParams(location.search).get('kode');if(c){setCode(c);void lookup(c).catch(()=>{})}else setLoading(false);return}void refresh();const t=setInterval(refresh,10000);return()=>clearInterval(t)},[customer]);
 useEffect(()=>{if(!customer||!trackingKey)return;const t=setInterval(()=>lookup(trackingKey).catch(()=>{}),10000);return()=>clearInterval(t)},[customer,trackingKey]);
 useEffect(()=>{if(!open||!normalizePhone(phone)){setExisting(null);return}const controller=new AbortController();const t=setTimeout(()=>fetch('/api/customers?lookup='+encodeURIComponent(phone),{signal:controller.signal}).then(r=>r.json()).then((d:any)=>setExisting(d.customer||null)).catch(()=>{}),400);return()=>{clearTimeout(t);controller.abort()}},[phone,open]);
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();Promise.resolve(context.registerTool({name:customer?'track_wash':'read_wash_queue',description:customer?'Lihat status cucian dengan nomor plat atau nomor HP sepatu.':'Baca daftar antrean yang diizinkan oleh sesi PIN karyawan.',inputSchema:{type:'object',properties:customer?{code:{type:'string'}}:{},required:customer?['code']:[],additionalProperties:false},annotations:{readOnlyHint:true},execute:async(input:any)=>{if(customer){if(typeof input.code!=='string'||!input.code.trim())throw Error('Isi plat atau nomor HP');return {jobs:await lookup(input.code)}}const r=await fetch('/api/jobs');const d=await r.json() as any;if(!r.ok)throw Error(d.error);setJobs(d.jobs);return {jobs:d.jobs}}},{signal:lifecycle.signal})).catch(()=>{});return()=>lifecycle.abort()},[customer]);
 function start(){setFormError('');setOpen(true)}
 async function create(e:React.FormEvent){e.preventDefault();setFormError('');setBusy(true);try{
  const body={category,customerName,phone,plate,vehicle,washType:selectedService,shoes:shoes.map(s=>({brand:s.brand,color:s.color}))};
  const r=await fetch('/api/jobs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json() as any;if(!r.ok)throw Error(d.error);
  setOpen(false);setPlate('');setVehicle('');setCustomerName('');setPhone('');setShoes([emptyShoe()]);setExtras([]);setExisting(null);setNotice(category==='sepatu'?`${d.count} pasang sepatu tersimpan. Pelanggan cukup cek dengan nomor HP.`:'Kendaraan tersimpan. Pelanggan cukup cek dengan nomor plat.');await refresh();
 }catch(e){setFormError((e as Error).message)}finally{setBusy(false)}}
 async function advance(j:Job){if(j.status===2){openPay(j,true);return}setBusy(true);try{const r=await fetch('/api/jobs',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:j.id,status:j.status+1})});const d=await r.json() as any;if(!r.ok)throw Error(d.error);setNotice(itemTitle(j)+' · '+labels[j.status+1]);await refresh()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function copy(j:Job){const url=location.origin+'/?kode='+encodeURIComponent(j.category==='sepatu'?(normalizePhone(j.phone)||j.id):j.plate);try{await navigator.clipboard.writeText(url);setNotice('Tautan status disalin.')}catch{setNotice('Tautan status: '+url)}}
 function openPay(j:Job,isCheckout=false){setCheckout(isCheckout);setMethod('qris');setPay(j);setPayAmount(j.amount===null?'':String(j.amount));setPayError('')}
 async function savePayment(e:React.FormEvent){e.preventDefault();if(!pay)return;setBusy(true);setPayError('');try{const r=await fetch('/api/jobs',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:pay.id,action:checkout?'checkout':'pay',amount:Number(payAmount),paymentMethod:method})});const d=await r.json() as any;if(!r.ok)throw Error(d.error);setPay(null);setNotice(checkout?'Pembayaran dan pengambilan selesai dicatat.':'Pembayaran berhasil dicatat.');await refresh()}catch(e){setPayError((e as Error).message)}finally{setBusy(false)}}
 const shown=jobs.filter(j=>(filter==='active'?j.status<3:filter==='all'?true:j.status===Number(filter))&&([j.plate,j.vehicle,j.customerName,j.phone,j.brand,j.color,j.washType,j.category].join(' ').toLowerCase().includes(query.toLowerCase())||(normalizePhone(query)&&normalizePhone(query)===normalizePhone(j.phone))));
 const groups=shown.reduce<Record<string,Job[]>>((g,j)=>{const key=dayKey(j.created);(g[key]??=[]).push(j);return g},{});
 const selectedService=category==='mobil'?carService(carClass,carPackage,extras):washType;
 const unitPrice=priceFor(category,selectedService)||0;
 const total=category==='sepatu'?shoes.length*SHOE_PRICE:unitPrice;
 return <div className="shell"><Header staff={!customer}/>{customer?<main className="customer"><span className="eyebrow">CEK CUCIAN SAYA</span><h1>Pantau cucian Anda.</h1><p className="lead">Gunakan nomor plat atau nomor HP saat pendaftaran.</p><WashingCounts/><form className="lookup" onSubmit={e=>{e.preventDefault();setTrackingKey('');void lookup(code).catch(()=>{})}}><label htmlFor="code">Nomor plat / No. HP</label><div><input id="code" value={code} onChange={e=>setCode(e.target.value)} placeholder="KB1234XX" autoComplete="off" spellCheck={false} maxLength={40} required/><button className="primary" disabled={busy}>Cek status<ArrowRight size={18}/></button></div><small>Nomor HP dapat ditulis 08…, 628…, atau +628….</small></form>{error&&<div className="error" role="alert">{error}</div>}
 {tracked.length>1&&<div className="track-summary"><strong>{tracked.length} {tracked.every(j=>j.category==='sepatu')?'pasang sepatu':'cucian'}</strong><span>{tracked.filter(j=>j.status===2).length} siap diambil · {tracked.filter(j=>j.status<2).length} dalam proses</span></div>}
 {tracked.map(j=><section className="tracking" key={j.id}><div className="track-head"><span className="car-icon"><ItemIcon category={j.category}/></span><div><h2>{itemTitle(j)}</h2><p>{itemDetail(j)}</p></div><span className={'badge s'+j.status}>{labels[j.status]}</span></div><h2>{['Cucian Anda sudah masuk antrean.','Cucian Anda sedang kami cuci.','Cucian Anda sudah bersih!','Terima kasih, sampai jumpa!'][j.status]}</h2><p>{['Status diperbarui ketika pencucian dimulai.','Kami sedang membersihkan cucian Anda dengan teliti.','Silakan temui karyawan untuk mengambil cucian Anda.','Cucian telah diambil. Terima kasih sudah memilih iT Wash.'][j.status]}</p><div className="timing"><span>Masuk<strong>{dateTime(j.created)}</strong></span>{j.category==='sepatu'&&<span>Estimasi pengambilan<strong>{dateTime(j.estimatedAt||j.created+48*3600000)}</strong><small>Perkiraan 48 jam; ikuti status Siap diambil.</small></span>}</div><ol className="steps">{labels.map((l,i)=><li className={i<=j.status?'done':''} key={l}><span>{i<j.status?<Check size={17}/>:i+1}</span>{l}</li>)}</ol></section>)}{tracked.length>0&&<div className="sync tracking-sync"><RefreshCw size={14}/> Diperbarui otomatis setiap 10 detik</div>}<Pricelist/></main>:<main className="staff-main"><div className="heading"><div><span className="eyebrow">AREA KARYAWAN</span><h1>Antrean cucian</h1><p className="lead">Mobil, motor, dan sepatu. Semua terpantau.</p></div><div className="heading-actions"><button className="secondary qris-button" onClick={()=>setQris(true)}><QrCode size={24}/> QRIS pembayaran</button><button className="primary add" onClick={start}><Plus size={20}/> Tambah cucian</button></div></div>
 <div className="summary">{labels.slice(0,3).map((l,i)=>{const Icon=icons[i];return <button key={l} className={'stat stat'+i} onClick={()=>setFilter(String(i))}><span className="stat-label"><Icon size={20}/>{l}</span><strong>{jobs.filter(j=>j.status===i).length.toString().padStart(2,'0')}</strong><span className="stat-bottom">{['Cucian dalam antrean','Cucian dalam pengerjaan','Cucian selesai dicuci'][i]}<ArrowRight size={17}/></span></button>})}</div>
 <section className="queue"><div className="queue-top"><h2>Daftar cucian <span>{jobs.filter(j=>j.status<3).length} aktif</span></h2><span className="sync"><RefreshCw size={14}/> Pembaruan otomatis</span></div><div className="toolbar"><Tabs value={filter} onValueChange={setFilter}><TabsList className="filters">{[['active','Aktif'],['0','Menunggu'],['1','Dicuci'],['2','Selesai'],['all','Semua']].map(([v,l])=><TabsTrigger key={v} value={v}>{l}</TabsTrigger>)}</TabsList></Tabs><label className="search"><Search size={18}/><input aria-label="Cari nama, plat, nomor HP, atau cucian" placeholder="Cari nama, plat, atau cucian…" value={query} onChange={e=>setQuery(e.target.value)}/></label></div>
 {error&&<div className="error" role="alert">{error}<button onClick={refresh}>Coba lagi</button></div>}{notice&&<div className="notice" role="status">{notice}<button aria-label="Tutup pemberitahuan" onClick={()=>setNotice('')}>×</button></div>}
 {loading?<div className="empty">Memuat antrean…</div>:shown.length===0?<div className="empty"><Footprints size={32}/><h3>Belum ada cucian di daftar ini</h3><p>{query?'Coba kata pencarian lain.':'Tambahkan cucian saat pelanggan datang.'}</p><button className="secondary" onClick={start}><Plus size={17}/> Tambah cucian</button></div>:Object.entries(groups).map(([key,rows])=><div key={key}><h3 className="date-group">{dayLabel(rows[0].created)}<span>{rows.length} cucian</span></h3>{rows.map(j=><article className="job" key={j.id}><span className="car-icon"><ItemIcon category={j.category}/></span><div className="vehicle"><h3>{itemTitle(j)}</h3><p>{itemDetail(j)}</p><p className="owner-line">{j.customerName||'Data pemilik belum tersedia'}{waLink(j)&&<> · <a href={waLink(j)} target="_blank" rel="noopener noreferrer" aria-label={'WhatsApp '+(j.customerName||'pelanggan')}>{normalizePhone(j.phone)} <MessageCircle size={13}/></a></>}</p><div className="job-times"><span>Masuk: {dateTime(j.created)}</span>{j.category==='sepatu'&&<span>Estimasi: {dateTime(j.estimatedAt||j.created+48*3600000)}</span>}</div></div><div className="job-right"><span className={'badge s'+j.status}>{labels[j.status]}</span><div className="job-actions">{j.status<3&&<button className={'action action'+j.status} disabled={busy} onClick={()=>advance(j)}>{['Mulai cuci','Selesai cuci','Sudah diambil'][j.status]}<ArrowRight size={16}/></button>}{j.status===2&&waLink(j)&&!canInvoice(j)&&<a className="whatsapp" href={waLink(j,true)} target="_blank" rel="noopener noreferrer"><MessageCircle size={17}/>Kabari via WA</a>}{canInvoice(j)&&waLink(j)&&<button className="whatsapp" onClick={()=>setInvoice(j)}><MessageCircle size={17}/> WA & invoice lunas</button>}{canInvoice(j)&&<button className="secondary invoice-button" onClick={()=>setInvoice(j)}>Invoice LUNAS</button>}<button className="copy" onClick={()=>copy(j)} title="Salin tautan status"><Copy size={16}/> Tautan</button></div><div className="payment-line">{j.paidAt?<span className="paid"><Check size={14}/> Lunas · {money(j.amount||0)} · {j.paymentMethod.toUpperCase()}</span>:<button onClick={()=>openPay(j)}><Wallet size={14}/> {j.amount===null?'Catat pembayaran':money(j.amount)+' · Belum dibayar'}</button>}</div></div></article>)}</div>)}
 </section><aside className="hint"><Droplets size={22}/><p>Mobil dan motor dicek dengan plat. Semua sepatu dalam satu pesanan dicek dengan nomor HP pemilik.</p></aside></main>}
 <Footer/><InvoiceDialog job={invoice} onClose={()=>setInvoice(null)}/>
 <Dialog open={open} onOpenChange={setOpen}><DialogContent className="wash-dialog"><DialogTitle className="modal-title">Tambah cucian</DialogTitle><DialogDescription>Satu pemilik, satu formulir. Tambahkan semua pasang sepatu di sini.</DialogDescription><form onSubmit={create} className="entry"><fieldset disabled={busy}><legend>Yang akan dicuci</legend><RadioGroup className="choice-grid" value={category} onValueChange={v=>{setCategory(v);setWashType('Basic');setExtras([])}} aria-label="Yang akan dicuci">{[['mobil','Mobil'],['motor','Motor'],['sepatu','Sepatu']].map(([v,l])=><label className={'choice '+(category===v?'chosen':'')} key={v}><RadioGroupItem value={v}/><ItemIcon category={v}/>{l}</label>)}</RadioGroup></fieldset>
 <div className="form-grid"><label>No. HP pemilik<input required type="tel" inputMode="tel" maxLength={22} placeholder="081234567890" value={phone} onChange={e=>setPhone(e.target.value)} onBlur={()=>{const p=normalizePhone(phone);if(p)setPhone(p)}}/><small>Format 08 otomatis menjadi 628.</small></label><label>Nama pemilik<input required maxLength={80} placeholder="Nama pelanggan" value={customerName} onChange={e=>setCustomerName(e.target.value)}/></label></div>
 {existing&&<div className="notice customer-match">Pelanggan terdaftar: <strong>{existing.name}</strong>. Nomor HP yang sama tetap tercatat sebagai satu pelanggan.<button type="button" onClick={()=>setCustomerName(existing.name)}>Gunakan nama ini</button></div>}
 {category==='sepatu'?<div className="shoe-list">{shoes.map((shoe,i)=><fieldset className="shoe-entry" key={shoe.key}><legend>Sepatu {i+1}</legend>{shoes.length>1&&<button type="button" className="remove-shoe" aria-label={'Hapus sepatu '+(i+1)} onClick={()=>setShoes(shoes.filter(s=>s.key!==shoe.key))}><Trash2 size={16}/> Hapus</button>}<div className="form-grid"><label>Merek sepatu<input required maxLength={60} value={shoe.brand} placeholder="Contoh: Nike" onChange={e=>setShoes(shoes.map(s=>s.key===shoe.key?{...s,brand:e.target.value}:s))}/></label><label>Warna sepatu<input required maxLength={40} value={shoe.color} placeholder="Contoh: putih" onChange={e=>setShoes(shoes.map(s=>s.key===shoe.key?{...s,color:e.target.value}:s))}/></label></div><div className="price-tag">Harga per pasang<strong>{money(SHOE_PRICE)}</strong></div></fieldset>)}<button type="button" className="secondary add-shoe" disabled={shoes.length>=30} onClick={()=>setShoes([...shoes,emptyShoe()])}><Plus size={18}/> Tambah sepatu</button><p className="field-note">{shoes.length} pasang · Estimasi pengambilan 48 jam setelah dicatat.</p></div>:<><div className="form-grid"><label>Nomor plat<input required maxLength={14} placeholder="KB1234XX" value={plate} onChange={e=>setPlate(e.target.value.toUpperCase())}/></label><label>Jenis kendaraan<input required maxLength={60} placeholder={category==='motor'?'Honda Vario 160':'Toyota Avanza'} value={vehicle} onChange={e=>setVehicle(e.target.value)}/></label></div>{category==='mobil'?<>
 <fieldset><legend>Kelas mobil</legend><RadioGroup className="choice-grid service-choices car-class-choices" value={carClass} onValueChange={setCarClass} aria-label="Kelas mobil">{Object.keys(CAR_PRICES).map(v=><label className={'choice '+(carClass===v?'chosen':'')} key={v}><RadioGroupItem value={v}/><span>{v}<small>{CAR_EXAMPLES[v]}</small></span></label>)}</RadioGroup></fieldset>
 <fieldset><legend>Paket cuci</legend><RadioGroup className="choice-grid service-choices" value={carPackage} onValueChange={v=>{setCarPackage(v);if(v==='Plus+')setExtras(extras.filter(x=>x!=='GLACO Front Glass Coating'))}} aria-label="Paket cuci">{CAR_PACKAGES.map(v=><label className={'choice '+(carPackage===v?'chosen':'')} key={v}><RadioGroupItem value={v}/><span>{v}<small>{money(CAR_PRICES[carClass][v])}</small></span></label>)}</RadioGroup><p className="field-note">{PACKAGE_DETAILS[carPackage]}</p></fieldset>
 <fieldset><legend>Layanan tambahan (opsional)</legend><div className="addon-choices">{Object.entries(ADD_ON_PRICES).map(([name,price])=>{const included=carPackage==='Plus+'&&name==='GLACO Front Glass Coating';return <label key={name}><input type="checkbox" checked={included||extras.includes(name)} disabled={included} onChange={e=>setExtras(e.target.checked?[...extras,name]:extras.filter(x=>x!==name))}/><span>{name}<small>{included?'Sudah termasuk Plus+':money(price)}</small></span></label>})}</div></fieldset>
 </>:<fieldset><legend>Tarif motor</legend><RadioGroup className="choice-grid service-choices" value={washType} onValueChange={setWashType} aria-label="Tarif motor">{Object.entries(MOTOR_PRICES).map(([name,price])=><label className={'choice '+(washType===name?'chosen':'')} key={name}><RadioGroupItem value={name}/><span>{name}<small>{money(price)}</small></span></label>)}</RadioGroup></fieldset>}<div className="price-tag">Harga cuci<strong>{money(unitPrice)}</strong></div></>}
 <div className="notice"><strong>Total: {money(total)}</strong>{category==='sepatu'&&<span> · {shoes.length} pasang × {money(SHOE_PRICE)}</span>}<br/>Pembayaran dicatat setelah pelanggan membayar.</div>{formError&&<p className="error" role="alert">{formError}</p>}<button className="primary" disabled={busy}>{busy?'Menyimpan…':category==='sepatu'?`Simpan ${shoes.length} pasang sepatu`:'Masukkan ke antrean'}<ArrowRight size={18}/></button></form></DialogContent></Dialog>
 <Dialog open={qris} onOpenChange={setQris}><DialogContent className="qris-dialog"><DialogTitle>QRIS pembayaran iT Wash</DialogTitle><DialogDescription>Scan kode di bawah. Pastikan nama penerima IT WASH.</DialogDescription><img src="/qris-itwash.jpg" alt="QRIS pembayaran IT WASH, NMID ID1025433287535"/><p className="field-note">Periksa pembayaran masuk sebelum mencatat transaksi sebagai lunas.</p></DialogContent></Dialog>
 <Dialog open={!!pay} onOpenChange={v=>{if(!v&&!busy)setPay(null)}}><DialogContent className="checkout-dialog"><DialogTitle>{checkout?'Pembayaran & pengambilan':'Catat pembayaran'}</DialogTitle><DialogDescription>{pay?itemTitle(pay):''}{checkout?' — konfirmasi sebelum menyerahkan cucian.':' — catat setelah pembayaran diterima.'}</DialogDescription><form className="entry" onSubmit={savePayment}>
{pay?.paidAt?<div className="notice"><strong>Sudah lunas · {money(pay.amount||0)}</strong><br/>{pay.paymentMethod.toUpperCase()} · {dateTime(pay.paidAt)}<br/>Pembayaran tidak akan dicatat ulang.</div>:<><label>Nominal pembayaran (Rp)<input required type="number" min="0" max="100000000" step="1" value={payAmount} readOnly={pay?.amount!==null} onChange={e=>setPayAmount(e.target.value)}/></label><fieldset><legend>Metode pembayaran</legend><RadioGroup className="choice-grid payment-methods" value={method} onValueChange={setMethod} aria-label="Metode pembayaran">{[['qris','QRIS'],['cash','Tunai']].map(([v,l])=><label className={'choice '+(method===v?'chosen':'')} key={v}><RadioGroupItem value={v}/>{l}</label>)}</RadioGroup></fieldset>{method==='qris'&&<div className="checkout-qris"><img src="/qris-itwash.jpg" alt="QRIS IT WASH untuk pembayaran"/><p>Pastikan pembayaran QRIS sudah masuk sebelum konfirmasi.</p></div>}</>}
{payError&&<p className="error" role="alert">{payError}</p>}<button className="primary" disabled={busy}>{busy?'Menyimpan…':checkout?(pay?.paidAt?'Konfirmasi sudah diambil':'Pembayaran diterima & sudah diambil'):'Konfirmasi pembayaran diterima'}</button></form></DialogContent></Dialog>
 </div>
}
